### ISSUE TITLE
probelm with uwu

### ISSUE THREAD

**Issue by acuaroo** [uwu/uwu#21]
I have been using uwu for so long now, just one problem with it.
Not enough uwu, needs an uwu folder to organize the uwu and needs a uwu.uwu file, this helps organize the uwu for new projetcs using uwu.

I am sure this would help out a lot of developers.

**Comment by relative** [comment]
uwu

**Comment by ghost** [comment]
uwu

**Comment by relative** [comment]
uwu

**Comment by acuaroo** [comment]
uwu?

**Comment by elegantShock2258** [comment]
i have been using uwu fow so wong n-nyow, σωσ just one p-pwobwem with it. >_<
n-nyot enough uwu, :3 n-nyeeds an uwu f-fowdew to owganize t-the uwu and nyeeds a-a uwu.uwu f-fiwe, (U ﹏ U) this hewps owganize the uwu fow nyew pwojetcs using uwu. -.-

i am suwe this wouwd h-hewp out a wot of devewopews. (ˆ ﻌ ˆ)♡
