### ISSUE TITLE
Possible uwu leak

### ISSUE THREAD

**Issue by DebitCardz** [uwu/uwu#23]
There is a possible uwu leak within this code.
```uwu
uwu
```
Though highly unlikely to actually occur I think it would be best to extensively test this code to make sure the uwu leak does not occur as it may throw a OutOfUwUException which may terminate the program.

I will do my own testing on this to see if the exception is thrown or not.

**Comment by elegantShock2258** [comment]
thewe is a possibwe uwu weak within t-this code.

> `uwu`

t-though highwy unwikewy t-to actuawwy o-occuw i think i-it wouwd be best t-to extensivewy t-test this code t-to make suwe the uwu weak does nyot occuw as it may thwow a outofuwuexception which may tewminate t-the pwogwam. -.-

i wiww do my own testing on this t-to see if the exception is thwown o-ow nyot. (ˆ ﻌ ˆ)♡
